# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jobs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\njobs.proto\")\n\x03Job\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\njob_status\x18\x02 \x01(\t2\"\n\nJobService\x12\x14\n\x06\x41\x64\x64Job\x12\x04.Job\x1a\x04.Jobb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jobs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOB._serialized_start=14
  _JOB._serialized_end=55
  _JOBSERVICE._serialized_start=57
  _JOBSERVICE._serialized_end=91
# @@protoc_insertion_point(module_scope)
